apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
  name: {{ .managedClusterName }}
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
